### ISSUE TITLE
assume bash as default shell when creating a new project

### ISSUE THREAD

**Issue by ilkosta** [ajwillia-ms/edi#3]
Hi,
I've tried to create a new project and after the wizard run I got this errors:

```shell
$| is not a valid variable in fish.
fish: sed -i "s|\${edi_name}|test_efl|g;s|\${Edi_Name}|test_efl|g;s|\${EDI_NAME}|TEST_EFL|g;s|\${Edi_User}|ilkosta|ig;s|\${Edi_Email}|....@....|g;s|\${Edi_Url}|$|g;s|\${Edi_Year}|2015|g" /home/costa/pkg/lav/test/test_efl//src/tests/test_test_efl.c
```

I don't know if this an issue related to `ecore_exec_run`, but seems that it use my default shell (fish) instead of /bin/sh.

**Comment by ajwillia-ms** [comment]
I can't replicate here for some reason but the creation script has been updated to use /bin/sh so it should remove the problems of your home shell behaving differently...

Please can you verify the fix?

**Comment by ilkosta** [comment]
it seems there is still a $ `$%s`, it's a typo?
There is also to fix the git scripts to use sh -c.

**Comment by ajwillia-ms** [comment]
Hi,

Thanks so much for the patch - it was indeed a typo and using /bin/sh for both creation scripts makes sense.
Of course there needs to be a windows friendly method going forward but that's another story...
