### ISSUE TITLE
run edi error.

### ISSUE THREAD

**Issue by martinXie** [ajwillia-ms/edi#6]
xiezd@Src-Tizen:~/work/efl/edi-0.3.0$ edi
edi: error while loading shared libraries: libelm_code.so.0: cannot open shared object file: No such file or directory

i have checked that  libelm_code.so.0 is local in /usr/local/lib.
xiezd@Src-Tizen:~/work/efl/edi-0.3.0$ ls /usr/local/lib | grep elm_code.so.0
libelm_code.so.0
libelm_code.so.0.3.0

**Comment by martinXie** [comment]
i'm a tizen developer, hope can use your ide tool to improve work.
hope you can give me respond.

**Comment by ajwillia-ms** [comment]
Hi, can you also please provide the output from:
'which edi'
and
'echo $LD_LIBRARY_PATH'
Also what platform you are on.
Thanks

**Comment by martinXie** [comment]
xiezd@Src-Tizen:~/work/efl/efl-1.17.0/src/tests/ecore$ which edi
/usr/local/bin/edi
xiezd@Src-Tizen:~/work/efl/efl-1.17.0/src/tests/ecore$ echo $LD_LIBRARY_PATH

xiezd@Src-Tizen:~/work/efl/efl-1.17.0/src/tests/ecore$ uname -a
Linux Src-Tizen 3.13.0-79-generic #123~precise1-Ubuntu SMP Fri Feb 19 14:48:42 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
xiezd@Src-Tizen:~/work/efl/efl-1.17.0/src/tests/ecore$ more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
xiezd@Src-Tizen:~/work/efl/efl-1.17.0/src/tests/ecore$

**Comment by martinXie** [comment]
xiezd@Src-Tizen:/etc/ld.so.conf.d$ cat /etc/ld.so.conf
include /etc/ld.so.conf.d/*.conf

xiezd@Src-Tizen:/etc/ld.so.conf.d$ cat /etc/ld.so.conf.d/libc.conf
# libc default configuration
/usr/local/lib

**Comment by ajwillia-ms** [comment]
This is strange. Can you try running ldconfig again and see it if helps?

**Comment by martinXie** [comment]
yes, now it can run normal. but there is a error message still.
xiezd@Src-Tizen:~/DEV-CoreApp-zhidong.xie/TZTV_2.4/MAIN2016/BROADCAST/Core-app_2016_Prj/DEV/APP2_zhidong.xie/tv-control/tv-viewer-app$ edi
ERR<29451>:eio lib/eio/eio_monitor.c:339 eio_monitor_stringshared_add() monitored path '/home/xiezd/.elementary/config/standard' not found.
Xlib:  extension "DPMS" missing on display "localhost:10.0".
Xlib:  extension "MIT-SCREEN-SAVER" missing on display "localhost:10.0".

**Comment by ajwillia-ms** [comment]
Thanks for the update. Don't worry about the error, that's stuff we need to tidy in the EFL.
